### ISSUE TITLE
Dashboard - system status information - Feature request

### ISSUE THREAD

**Issue by Cloolalang** [iotappstory/ESP-Library#108]
Hey, I had an issue which turned out not to be on my side, it was fixed quickly and it is working great now. 
However I spent 3 hrs trouble-shooting my NodeMCU project in my lab.
 It would be really good to know when the server is having issues/uprades/outages etc. 
Perhaps on the spare dash board window in the bottom right-hand side?
P

**Comment by Onno-Dirkzwager** [comment]
Will do! We have something in the works.
