### ISSUE TITLE
Problem with Authorization Code

### ISSUE THREAD

**Issue by RZachmann** [iotappstory/ESP-Library#139]
When I sign in to the control panel and press the "Generate Act. Code" button nothing happens.  Also, the Config mode of the device does not ask for the Authorization Code.  Because of this my device will not update. Is there a way to get an Authorization Code.  I don't remember ever having one.  Can you help?

**Comment by CwlBroeders** [comment]
@RZachmann 

Are u still having this problem?

**Comment by RZachmann** [comment]
Thank you. I found the problem I needed to add headers to the program.



Sent via the Samsung Galaxy S8+, an AT&T 5G Evolution capable smartphone



-------- Original message --------
