### ISSUE TITLE
Details of use?

### ISSUE THREAD

**Issue by jmoudy** [iotappstory/ESP-Library#155]
Loving IOTAPPSTORY ... I have a few questions.

- Does this application powerdown the Wifi when it is not being used to check for updates? 
- I know the wifi library calls are available, but can I power down the wifi without causing a problem for IOTAPPSTORY? 
- Also, if so, can I bring up the wifi system, then make a call to check for update, then I'll power down the wifi?

**Comment by Onno-Dirkzwager** [comment]
@jmoudy 
- The library does not power down Wifi
- Yes you can! It is wise to take full controle... don't use the update interval but only [callhome](https://iotappstory.com/wiki/arduino-esp/library-api-20/api-methods/callhome()) when your conditions are met.... awake, connected etc.

**Comment by Onno-Dirkzwager** [comment]
@jmoudy does this answer your question? If so please close the issue.

**Comment by Onno-Dirkzwager** [comment]
@jmoudy closing issue due to lack of response.
Feel free to reopen if deemed necessary

**Comment by jmoudy** [comment]
Thanks, I'll work on getting an example built. Waiting for new hardware. 

Jim
