### ISSUE TITLE
https://iotappstory.com/ota/config/cfg.js not found

### ISSUE THREAD

**Issue by Valdhor** [iotappstory/ESP-Library#164]
The config page on initial setup requires a javascript file at https://iotappstory.com/ota/config/cfg.js but this URL gives a 404 not found and all you get is a blank page.

**Comment by CwlBroeders** [comment]
Thank you for pointing this out @Valdhor
While doing some remoddeling on the backend the cached routing was not reset.

Route works again now.

**Comment by Valdhor** [comment]
Thank you. That fixed it. Onwards...
