### ISSUE TITLE
Doesn’t work with PlatformIO 

### ISSUE THREAD

**Issue by Valdhor** [iotappstory/ESP-Library#167]
Should this work with PlatformIO? When I try to compile the initial application I get “Can’t find FS.h”. I don’t know where to find that library.

**Comment by CwlBroeders** [comment]
This is the ESP arduino core file system library (it replaces the SPIFFS library).
https://github.com/esp8266/Arduino/blob/master/cores/esp8266/FS.h

**Comment by Valdhor** [comment]
It looks like this is for esp8266 but I have esp32. Is this still correct?

**Comment by CwlBroeders** [comment]
For ESP32 this should also be present in the core framework.
https://github.com/espressif/arduino-esp32/blob/master/libraries/FS/src/FS.h

https://community.platformio.org/t/errors-when-compiling-esp32-code/11421

**Comment by Valdhor** [comment]
Thanks for that. I will give it a try.

I’m thinking the question is why I need to install that as a separate install? Perhaps an update to the documentation?

**Comment by Valdhor** [comment]
I do appreciate the quick response.

**Comment by CwlBroeders** [comment]
The documentation is (for now) mainly tailored to the arduino IDE, aswell as being slightly outdated.

**Comment by Valdhor** [comment]
Figured out you have to have lib_deps in the right order.
