### ISSUE TITLE
WLAN password field too short

### ISSUE THREAD

**Issue by reibuehl** [iotappstory/ESP-Library#51]
The config variable "password" is defined as char password[STRUCT_CHAR_ARRAY_SIZE]; in IOTAppStory.h and STRUCT_CHAR_ARRAY_SIZE is set to 50 there while WPA2 passwords can be up to 63 characters long. 
Please define STRUCT_PASSWORD_SIZE = 64 and then use that length for the password.

**Comment by Onno-Dirkzwager** [comment]
Reibuehl,
thanks for the feedback. Will do, in the meantime you can change it in the .h file.

**Comment by reibuehl** [comment]
IOTAppStory.cpp also uses the define in three locations. I changed all to use a new define STRUCT_PASSWORD_SIZE but still can't connect and the debug output shows that only 49 chars are read. It seems that there is another limit on the HTML input field that I didn't find yet.

**Comment by reibuehl** [comment]
The maximum field length is also used once in WiFiManagerMod.h. After changing that to 63 in the HTML code, it seems to work.

**Comment by Onno-Dirkzwager** [comment]
Reibuehl,
which version of the lib are you using? 2.0.0?

**Comment by reibuehl** [comment]
No, the 1.0.6 from the Arduino Library Manager.

**Comment by Onno-Dirkzwager** [comment]
You might be interested in the upcoming lib 2.0.0
Its not in Lib Manager yet. You can download it straight from the master.
We are currently working on the documentation, website, video etc. So the best documentation we have currently is the readme file in the master.

**Comment by Onno-Dirkzwager** [comment]
Hi Reibuehl,
I implemented your suggestion into the master (2.0.0)
