### ISSUE TITLE
Wifi won't connect to hidden ssid's.  

### ISSUE THREAD

**Issue by rcojoe** [iotappstory/ESP-Library#59]
I successfully connect to a wifi ap when the ssid is broadcasted. If I hid the SSID, it fails to connect and defaults to AP mode.

**Comment by Onno-Dirkzwager** [comment]
Hi rcojoe,
which version of the library are you using?

**Comment by rcojoe** [comment]
Latest build. 2.0

**Comment by Onno-Dirkzwager** [comment]
(Y) We will get back to you.

**Comment by Onno-Dirkzwager** [comment]
Rcojoe,
this is an issue in the underlying wifimulti library [#2246](https://github.com/esp8266/Arduino/issues/2246)

As a workaround you can turn off the wifimulti option in the IOTAppStory.h or config.h file (depending on version)

>> set the #define WIFI_MULTI to false <<

**Comment by rcojoe** [comment]
Yes. Please close. This is resolved.

**Comment by Onno-Dirkzwager** [comment]
(Y)
