### ISSUE TITLE
One backslash too much escaping HTML code

### ISSUE THREAD

**Issue by Bolukan** [iotappstory/ESP-Library#76]
One backslash too much in HTTP_WIFI_FORM[] and should be removed (errors compiling):

https://github.com/iotappstory/ESP-Library/blob/4f2a4bc71c108c26ee5554d0c5f8226862110705/src/IOTAppStory.h#L129

`onclick=\"ld('\wsa')\"` should be `onclick=\"ld('wsa')\"`

**Comment by Onno-Dirkzwager** [comment]
I think this is actually an typo and not an escaping backslash.
onclick=\"ld('/wsa')\"   as in root directory. (not that there is any other so leaving it out should work)

Ill let you know monday.

**Comment by Onno-Dirkzwager** [comment]
Closing as you already Pull requested a solutions.
